### ISSUE TITLE
Error when loading json config for Enrich 2

### ISSUE THREAD

**Issue by durr1602** [odcambc/dumpling#8]
Hi,
I am running dumpling successfully to about 90-92% done (in terms of jobs in the workflow), however I encounter an issue when running Enrich 2 (it appears to be raised when running the [main](https://github.com/FowlerLab/Enrich2/blob/main/enrich2/main.py)). Here is the error:
```
Traceback (most recent call last):
  File "/project/chlandry/users/rodur28/dumpling/.snakemake/conda/67d2d89bb9799e59a640f480438207d3_/lib/python3.13/site-packages/enrich2/main.py", line 160, in main_cmd
    cfg = json.load(open(args.config, "U"))
                    ~~~~^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'U'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/chlandry/users/rodur28/dumpling/.snakemake/conda/67d2d89bb9799e59a640f480438207d3_/bin/enrich_cmd", line 8, in <module>
    sys.exit(main_cmd())
             ~~~~~~~~^^
  File "/project/chlandry/users/rodur28/dumpling/.snakemake/conda/67d2d89bb9799e59a640f480438207d3_/lib/python3.13/site-packages/enrich2/main.py", line 164, in main_cmd
    raise ValueError("Improperly formatted .json file [{}]".format(DRIVER_NAME))
ValueError: Improperly formatted .json file [enrich_cmd]
```
I was getting the same error when trying to run dumpling on a dataset with only two time points, which meant the JSON config file was almost empty, but I've corrected this and now it looks ok to me (see [attached file](https://github.com/user-attachments/files/18084357/benchmark_RD_config.json))
Thanks for your help!

**Comment by odcambc** [comment]
Ah, this was a silly one by me, I forgot to merge my updated branch into main. This should be fixed now. Could you try again? Hopefully nothing else pops up...

**Comment by durr1602** [comment]
Thanks ! I think it's good, I do get another problem (sorry about that..) but it appears to be related to rosace. The enrich2 steps has successfully created all h5 files ;)

**Comment by odcambc** [comment]
Thank you for submitting these issues! Sorry for the bugs, but I appreciate the opportunity to resolve them :)
